name: google_maps_place_picker_mb
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 3.1.2
homepage: https://github.com/martin-braun-net/google_maps_place_picker_mb

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=3.16.1"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  google_api_headers: ^3.2.1
  google_maps_flutter: ^2.5.0
  flutter_google_maps_webservices: ^1.1.1
  http: ^1.1.0
  provider: ^6.0.5
  tuple: ^2.0.2
  uuid: ^4.1.0
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

false_secrets:
  - /example/lib/keys.dart
  - /example/android/app/src/main/AndroidManifest.xml
  - /example/ios/Runner/AppDelegate.swift
